name: MacOS

on:
  push:
    branches-ignore: [ '**win**', '**android**', '**linux**', '**bsd**', '**haiku**', '**wasm**', '**ios**' ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  LANG: en_US.UTF-8
  LC_CTYPE: UTF-8
  BROWSER: open

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/toolchain@v1
        name: Install Rust Toolchain
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: Compile
        with:
          command: build
      - run: |
          which open
          open "http://127.0.0.1:49750/macos/ｎｏｎａｓｃｉｉ"
        name: op
      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test
          args: --all --locked --verbose
      - uses: actions-rs/cargo@v1
        name: Check Code Formatting
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: Lints
        with:
          command: clippy
          args: --all-targets -- -D warnings
